[package]
name = "bf16-to-fp16"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
candle-core = "0.9.1"
clap = { version = "4.5", features = ["derive"] }
hf-hub = "0.4"
safetensors = "0.7"
