[package]
name = "s3-upload"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
aws-config = "1.1"
aws-sdk-s3 = "1.14"
aws-types = "1.1"
clap = { version = "4.5", features = ["derive"] }
md5 = "0.7"
tokio = { version = "1", features = ["full"] }
walkdir = "2.5"
hex = "0.4"
